### ISSUE TITLE
[Windows]关于var_maxfd限制

### ISSUE THREAD

**Issue by sidyhe** [acl-dev/libfiber#4]
在Windows下SOCKET的最大值并不确定
看您在Windows下的实现是固定的10240上限

实际测试当运行多个client.exe时, 会触发
```C++
msg_error("fd: %d >= setsize: %d", fe->fd, ev->setsize);
```
导致拒绝服务
另外看实现是根据这个size用于分配数组, 为了O(1)查找吧
是否可以修改为不限制此大小, 或用htable解决此问题?

**Comment by zhengshuxin** [comment]
增加了函数：acl_fiber_set_fdlimit 用来设置 fd 最大值；另外，在 WIN 下，因为 fd 是不连续的，所以查找方式采用了 htable，而在 Unix 平台下则是用数组直接定位，所以相对而言 Unix 平台下的效率会更高。
